// <auto-generated />
namespace CQSLab.Business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddLanguagesEntites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLanguagesEntites));
        
        string IMigrationMetadata.Id
        {
            get { return "201503181512212_Add-Languages-Entites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
